class Bag:
    red: int
    green: int
    blue: int
    def __init__(self, red: int, green: int, blue: int) -> Bag: ...
    
    @staticmethod
    def from_string(s: str) -> Bag: ...

    def can_contain(self, other: Bag) -> bool: ...
    def power(self) -> int: ...
    
class Game:
    id: int

    @staticmethod
    def from_string(s: str) -> Game: ...

    def check(self, bag: Bag) -> bool: ...
    def max_values(self) -> Bag: ...
    
